# Generated by Django 5.1 on 2024-11-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_alter_listing_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.FloatField(),
        ),
        migrations.RemoveField(
            model_name="comment",
            name="author",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="listing",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="watchlist",
        ),
        migrations.DeleteModel(
            name="Bid",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
