# Generated by Django 5.1 on 2024-11-28 15:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_alter_listing_price_remove_comment_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="listingWatchlist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
